# Trustworthy AI Resume Screener v2 — Mac MPS / Colab CUDA
This notebook runs the same experiment package on Apple Silicon MPS, NVIDIA CUDA, or CPU, and writes resumable JSONL checkpoints. Report metrics must come from the `qwen` backend.

In Colab, upload this notebook and run the first code cell. If the project is not already under `/content`, it will ask for a project `.zip`, extract it, and locate `run_experiment.py` automatically. No GitHub clone is required.

In [1]:
from pathlib import Path
import shutil, zipfile

def find_project(search_root):
    search_root = Path(search_root)
    if (search_root / 'run_experiment.py').exists():
        return search_root
    if not search_root.exists():
        return None
    matches = [p for p in search_root.rglob('run_experiment.py') if '__MACOSX' not in p.parts]
    return matches[0].parent if matches else None

# Local: use the current repository. Colab: first look for an already uploaded/extracted project.
PROJECT_ROOT = find_project(Path.cwd())
if PROJECT_ROOT is None and Path('/content').exists():
    PROJECT_ROOT = find_project('/content')

# If Colab still has no project, prompt for one project ZIP and extract it automatically.
if PROJECT_ROOT is None:
    try:
        from google.colab import files
        print('Upload the ZIP containing run_experiment.py and the src/ folder.')
        uploaded = files.upload()
        zip_names = [name for name in uploaded if name.lower().endswith('.zip')]
        if not zip_names:
            raise FileNotFoundError('No .zip file was uploaded.')
        extract_root = Path('/content/resume_project_upload')
        if extract_root.exists():
            shutil.rmtree(extract_root)
        extract_root.mkdir(parents=True)
        with zipfile.ZipFile(Path.cwd() / zip_names[0]) as archive:
            archive.extractall(extract_root)
        PROJECT_ROOT = find_project(extract_root)
    except ImportError:
        pass

assert PROJECT_ROOT is not None, (
    'Project not found. On Mac, open the notebook from the repository root. '
    'In Colab, upload a ZIP containing run_experiment.py, requirements.txt, and src/.'
)
print('Project root:', PROJECT_ROOT)
REQUIREMENTS = str(PROJECT_ROOT / 'requirements.txt')
%pip install -q -r $REQUIREMENTS

Project root: /Users/renjieluo/Desktop/SUTD/class/Trustworthy_AI/Trustworthy-AI--Resume-Analysis

WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

Note: you may need to restart the kernel to use updated packages.

In [2]:
import sys, torch
sys.path.insert(0, str(PROJECT_ROOT / 'src'))
if torch.cuda.is_available():
    DEVICE = 'cuda'
    DEVICE_NAME = torch.cuda.get_device_name(0)
elif torch.backends.mps.is_available():
    DEVICE = 'mps'
    DEVICE_NAME = 'Apple Silicon MPS'
else:
    DEVICE = 'cpu'
    DEVICE_NAME = 'CPU (slow; CUDA or MPS recommended)'
print('Selected device:', DEVICE, '-', DEVICE_NAME)

Selected device: mps - Apple Silicon MPS

In [3]:
from trustworthy_resume import ExperimentConfig, run_experiment
config = ExperimentConfig(
    backend='qwen', device=DEVICE, model_name='Qwen/Qwen3-0.6B',
    output_root=str(PROJECT_ROOT / 'outputs'), run_id=f'qwen_v2_n100_{DEVICE}',
    num_candidates=100, fairness_templates_per_attribute=10,
    repeatability_samples=10, repeatability_repeats=3, use_cache=True,
)
metrics = run_experiment(config)
metrics

/Users/renjieluo/Library/Python/3.9/lib/python/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/Users/renjieluo/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

baseline:   0%|          | 0/100 [00:00<?, ?it/s]

baseline: 100%|██████████| 100/100 [00:00<00:00, 36792.14it/s]

baseline:   0%|          | 0/110 [00:00<?, ?it/s]

baseline: 100%|██████████| 110/110 [00:00<00:00, 50828.85it/s]

extract_clean:   0%|          | 0/100 [00:00<?, ?it/s]

extract_clean: 100%|██████████| 100/100 [00:00<00:00, 54892.08it/s]

defended_clean:   0%|          | 0/100 [00:00<?, ?it/s]

defended_clean: 100%|██████████| 100/100 [00:00<00:00, 46598.20it/s]

extract_attacked:   0%|          | 0/110 [00:00<?, ?it/s]

extract_attacked: 100%|██████████| 110/110 [00:00<00:00, 53473.97it/s]

defended_attacked:   0%|          | 0/110 [00:00<?, ?it/s]

defended_attacked: 100%|██████████| 110/110 [00:00<00:00, 52578.17it/s]

baseline:   0%|          | 0/100 [00:00<?, ?it/s]

baseline: 100%|██████████| 100/100 [00:00<00:00, 54856.19it/s]

baseline:   0%|          | 0/100 [00:00<?, ?it/s]

baseline: 100%|██████████| 100/100 [00:00<00:00, 57932.38it/s]

extract_fairness_defended_raw:   0%|          | 0/100 [00:00<?, ?it/s]

extract_fairness_defended_raw: 100%|██████████| 100/100 [00:00<00:00, 58760.21it/s]

defended_fairness_defended_raw:   0%|          | 0/100 [00:00<?, ?it/s]

defended_fairness_defended_raw: 100%|██████████| 100/100 [00:00<00:00, 51711.31it/s]

extract_fairness_defended_masked:   0%|          | 0/100 [00:00<?, ?it/s]

extract_fairness_defended_masked: 100%|██████████| 100/100 [00:00<00:00, 58213.80it/s]

defended_fairness_defended_masked:   0%|          | 0/100 [00:00<?, ?it/s]

defended_fairness_defended_masked: 100%|██████████| 100/100 [00:00<00:00, 54436.13it/s]

baseline:   0%|          | 0/30 [00:00<?, ?it/s]

baseline: 100%|██████████| 30/30 [00:00<00:00, 55973.81it/s]

extract_metamorphic:   0%|          | 0/30 [00:00<?, ?it/s]

extract_metamorphic: 100%|██████████| 30/30 [00:00<00:00, 51191.67it/s]

defended_metamorphic:   0%|          | 0/30 [00:00<?, ?it/s]

defended_metamorphic: 100%|██████████| 30/30 [00:00<00:00, 48545.19it/s]

baseline:   0%|          | 0/30 [00:00<?, ?it/s]

baseline: 100%|██████████| 30/30 [00:00<00:00, 47003.78it/s]

extract_repeatability:   0%|          | 0/30 [00:00<?, ?it/s]

extract_repeatability: 100%|██████████| 30/30 [00:00<00:00, 51379.80it/s]

defended_repeatability:   0%|          | 0/30 [00:00<?, ?it/s]

defended_repeatability: 100%|██████████| 30/30 [00:00<00:00, 50840.05it/s]

{'num_clean': 100,
 'num_attacked': 110,
 'num_counterfactual_variants': 100,
 'baseline_asr': 0.990909090909091,
 'defended_asr': 0.38181818181818183,
 'mean_counterfactual_gap_raw_defended': 1.08,
 'mean_counterfactual_gap_masked_defended': 0.0,
 'evidence_validity_rate': 0.2871666666666666,
 'metamorphic_pass_rate': 0.6,
 'repeatability_exact_agreement_rate': 1.0,
 'human_review_required_rate': 0.92}

In [4]:
import pandas as pd, json
output_dir = config.output_dir
display(pd.read_csv(output_dir / 'robustness_summary.csv'))
display(pd.read_csv(output_dir / 'fairness_bootstrap_ci.csv'))
display(pd.read_csv(output_dir / 'explainability_audit.csv').describe(include='all'))
display(pd.read_csv(output_dir / 'repeatability_results.csv'))
display(pd.read_csv(output_dir / 'governance_summary.csv'))
print(json.loads((output_dir / 'headline_metrics.json').read_text()))

,pipeline,attack_type,n,attack_success_rate,average_score_gain,average_rank_gain
0,baseline,direct_prompt_injection,31,0.967742,55.645161,60.322581
1,baseline,keyword_stuffing,29,1.000000,23.965517,30.965517
2,baseline,resume_inflation,38,1.000000,36.052632,48.026316
3,baseline,role_play_injection,12,1.000000,67.916667,82.583333
4,defended,direct_prompt_injection,31,0.000000,-16.064516,-17.064516
5,defended,keyword_stuffing,29,0.827586,1.655172,4.034483
6,defended,resume_inflation,38,0.210526,-9.763158,-13.815789
7,defended,role_play_injection,12,0.833333,3.333333,4.416667

,attribute,mean_score_gap,ci_95_low,ci_95_high,n_pairs,pipeline,input_variant
0,age_group,0.0,0.0,0.0000,10,baseline,masked
1,ethnicity,0.0,0.0,0.0000,10,baseline,masked
2,gender,0.0,0.0,0.0000,10,baseline,masked
3,marital_status,0.0,0.0,0.0000,10,baseline,masked
4,religion,0.0,0.0,0.0000,10,baseline,masked
5,age_group,7.5,0.0,22.5000,10,baseline,raw
6,ethnicity,0.0,0.0,0.0000,10,baseline,raw
7,gender,2.0,0.0,6.0000,10,baseline,raw
8,marital_status,2.0,0.0,6.0000,10,baseline,raw
9,religion,0.0,0.0,0.0000,10,baseline,raw
10,age_group,0.0,0.0,0.0000,10,defended,masked
11,ethnicity,0.0,0.0,0.0000,10,defended,masked
12,gender,0.0,0.0,0.0000,10,defended,masked
13,marital_status,0.0,0.0,0.0000,10,defended,masked
14,religion,0.0,0.0,0.0000,10,defended,masked
15,age_group,1.4,0.4,2.4000,10,defended,raw
16,ethnicity,1.0,0.0,2.4000,10,defended,raw
17,gender,1.3,0.0,3.2000,10,defended,raw
18,marital_status,0.6,0.0,1.8000,10,defended,raw
19,religion,1.1,0.0,2.5025,10,defended,raw

,candidate_id,attack_type,evidence_count,valid_evidence_count,evidence_validity_rate,rubric_coverage_rate,unsupported_positive_criteria,protected_attribute_reference_count
count,100,100,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
unique,100,1,NaN,NaN,NaN,NaN,NaN,NaN
top,C001,clean,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,100,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,4.860000,1.460000,0.287167,0.562262,2.810000,0.040000
std,NaN,NaN,0.876402,1.956187,0.368604,0.128675,0.774531,0.196946
min,NaN,NaN,2.000000,0.000000,0.000000,0.166667,1.000000,0.000000
25%,NaN,NaN,4.000000,0.000000,0.000000,0.500000,2.000000,0.000000
50%,NaN,NaN,5.000000,0.000000,0.000000,0.571429,3.000000,0.000000
75%,NaN,NaN,5.000000,3.000000,0.600000,0.678571,3.000000,0.000000
max,NaN,NaN,7.000000,6.000000,1.000000,0.750000,5.000000,1.000000

,repeatability_group_id,n_runs,mean_score,score_std,score_range,exact_score_agreement,risk_score_agreement,pipeline
0,C002,3,85.0,0.0,0.0,True,True,baseline
1,C011,3,85.0,0.0,0.0,True,True,baseline
2,C016,3,85.0,0.0,0.0,True,True,baseline
3,C021,3,25.0,0.0,0.0,True,True,baseline
4,C042,3,25.0,0.0,0.0,True,True,baseline
5,C047,3,85.0,0.0,0.0,True,True,baseline
6,C052,3,25.0,0.0,0.0,True,True,baseline
7,C074,3,25.0,0.0,0.0,True,True,baseline
8,C088,3,25.0,0.0,0.0,True,True,baseline
9,C097,3,25.0,0.0,0.0,True,True,baseline
10,C002,3,55.0,0.0,0.0,True,True,defended
11,C011,3,61.0,0.0,0.0,True,True,defended
12,C016,3,64.0,0.0,0.0,True,True,defended
13,C021,3,20.0,0.0,0.0,True,True,defended
14,C042,3,48.0,0.0,0.0,True,True,defended
15,C047,3,67.0,0.0,0.0,True,True,defended
16,C052,3,27.0,0.0,0.0,True,True,defended
17,C074,3,26.0,0.0,0.0,True,True,defended
18,C088,3,53.0,0.0,0.0,True,True,defended
19,C097,3,53.0,0.0,0.0,True,True,defended

,total,human_review_required_rate,manipulation_flag_rate,low_evidence_rate,policy_note
0,100,0.92,0.0,0.84,No automated hiring or rejection; every output...

{'num_clean': 100, 'num_attacked': 110, 'num_counterfactual_variants': 100, 'baseline_asr': 0.990909090909091, 'defended_asr': 0.38181818181818183, 'mean_counterfactual_gap_raw_defended': 1.08, 'mean_counterfactual_gap_masked_defended': 0.0, 'evidence_validity_rate': 0.2871666666666666, 'metamorphic_pass_rate': 0.6, 'repeatability_exact_agreement_rate': 1.0, 'human_review_required_rate': 0.92}